[general]
import = ["~/.config/alacritty/themes/dracula.toml"]

[font]
normal.family = "JetBrainsMonoNL Nerd Font Mono"
bold.family = "JetBrainsMonoNL Nerd Font Mono"
italic.family = "JetBrainsMonoNL Nerd Font Mono"
bold_italic.family = "JetBrainsMonoNL Nerd Font Mono"
size = 17.0

[window.dimensions]
columns = 115
lines = 40

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001B\r"
