---
- hosts: localhost
  connection: local
  gather_facts: true
  vars:
    user: "{{ lookup('env', 'USER') }}"
    home: "{{ lookup('env', 'HOME') }}"
    distribution: "{{ ansible_distribution | lower }}"
  roles:
    - role: system
      become: true
      tags: sys
    - role: desktop
      tags: desktop
    - role: development
      tags: dev
