---
- name: Configure CAPS LOCK as an additional control
  ansible.builtin.shell: |
    {{ kwriteconfig }} --file {{ (home, '.config', 'kxkbrc') | path_join }} \
      --group Layout \
      --key Options \
      'caps:ctrl_modifier,shift:both_capslock_cancel'

- name: Configure dark theme
  ansible.builtin.shell: |
    {{ kwriteconfig }} --file {{ (home, '.config', 'kdeglobals') | path_join }} \
      --group KDE \
      --key LookAndFeelPackage \
      'org.kde.breezedark.desktop'

- name: Configure google chrome as default browser
  ansible.builtin.shell: |
    {{ kwriteconfig }} --file {{ (home, '.config', 'kdeglobals') | path_join }} \
      --group General \
      --key BrowserApplication \
      'google-chrome.desktop'

- name: Create a new konsole profile
  ansible.builtin.shell: |
    {{ kwriteconfig }} --file {{ (home, '.config', 'kdeglobals') | path_join }} \
      --group General \
      --key BrowserApplication \
      'google-chrome.desktop'