---
- name: Create konsole profile
  block:
    - name: Create konsole profile directory
      ansible.builtin.file:
        dest: "{{ (home, '.local', 'share', 'konsole') | path_join }}"
        state: directory

    - name: Create profile
      ansible.builtin.file:
        src: "{{ (role_path, 'files', 'konsole', 'Default.profile') | path_join }}"
        dest: "{{ (home, '.local', 'share', 'konsole') | path_join }}"
        state: link

- name: Configure CAPS LOCK as an additional control
  ansible.builtin.shell: |
    {{ kwriteconfig }} --file {{ (home, '.config', 'kxkbrc') | path_join }} \
      --group Layout \
      --key Options \
      'caps:ctrl_modifier,shift:both_capslock_cancel'

- name: Configure dark theme
  ansible.builtin.shell: |
    {{ kwriteconfig }} --file {{ (home, '.config', 'kdeglobals') | path_join }} \
      --group KDE \
      --key LookAndFeelPackage \
      'org.kde.breezedark.desktop'

- name: Configure google chrome as default browser
  ansible.builtin.shell: |
    {{ kwriteconfig }} --file {{ (home, '.config', 'kdeglobals') | path_join }} \
      --group General \
      --key BrowserApplication \
      'google-chrome.desktop'

- name: Set default Konsole profile
  ansible.builtin.shell: |
    {{ kwriteconfig }} --file {{ (home, '.config', 'konsolerc') | path_join }} \
      --group 'Desktop Entry' \
      --key DefaultProfile \
      'Default.profile'