---
- name: Configure app-switcher
  ansible.builtin.shell: gsettings set org.gnome.shell.app-switcher current-workspace-only true

- name: Enable user extensions
  ansible.builtin.shell: gsettings set org.gnome.shell disable-user-extensions false

- name: Configure CAPS LOCK as an additional control
  ansible.builtin.shell: gsettings set org.gnome.desktop.input-sources xkb-options "['caps:ctrl_modifier', 'shift:both_capslock_cancel']"

# You need to restart gnome to update the extensions installed list and
# After that you can run the bootstrap.sh again
# If your are using xrog, you can try to reload gnome (do not work for wayland)
- name: Enable gnome extensions
  ansible.builtin.shell: |
    gnome-extensions enable "$(gnome-extensions list | grep drive-menu)"
    gnome-extensions enable "$(gnome-extensions list | grep dash-to-dock)"
    gnome-extensions enable "$(gnome-extensions list | grep appindicator)"
  ignore_errors: true

- name: Configure dark mode
  ansible.builtin.shell: |
    gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-dark'
    gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'

- name: Configure touchpad
  ansible.builtin.shell: |
    gsettings set org.gnome.desktop.peripherals.touchpad send-events 'disabled-on-external-mouse'
    gsettings set org.gnome.desktop.peripherals.touchpad tap-to-click true

# https://askubuntu.com/questions/1036473/ubuntu-18-how-to-cha nge-screenshot-application-to-flameshot
- name: Configure flameshot as default screenshot tool
  ansible.builtin.shell: |
    gsettings set org.gnome.shell.keybindings show-screenshot-ui '[]'
    gsettings set org.gnome.settings-daemon.plugins.media-keys custom-keybindings "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/']"
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ name 'flameshot'
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ command '/usr/bin/flameshot gui'
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ binding 'Print'

- name: Disable gnome keyring ssh autostart
  ansible.builtin.shell: |
    mkdir -p ~/.config/autostart/
    cp /etc/xdg/autostart/gnome-keyring-ssh.desktop ~/.config/autostart/
    echo "Hidden=true" >> ~/.config/autostart/gnome-keyring-ssh.desktop

- name: Install home files
  ansible.builtin.file:
    src: "{{ (role_path, 'files', item) | path_join }}"
    dest: "{{ (home, item) | path_join }}"
    state: link
  loop:
    - .zsh
    - .zshrc
    - .zshenv
    - .aliases
    - .bkp_ignorelist

- name: Configure weechat
  ansible.builtin.file:
    src: "{{ (role_path, 'files', 'weechat') | path_join }}"
    dest: "{{ (home, '.config', 'weechat') | path_join }}"
    state: link

- name: Create gpg and ssh config directories
  ansible.builtin.file:
    dest: "{{ (home, item) | path_join }}"
    state: directory
    mode: 0700
  loop:
    - .ssh
    - .gnupg

- name: Configure gpg agent
  ansible.builtin.file:
    src: "{{ (role_path, 'files', 'gpg-agent.conf') | path_join }}"
    dest: "{{ (home, '.gnupg', 'gpg-agent.conf') | path_join }}"
    state: link
