---
- name: Configure CAPS LOCK as an additional control
  ansible.builtin.shell: gsettings set org.gnome.desktop.input-sources xkb-options "['caps:ctrl_modifier', 'shift:both_capslock_cancel']"

- name: Configure dark mode
  ansible.builtin.shell: |
    gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-dark'
    gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'

- name: Configure touchpad
  ansible.builtin.shell: |
    gsettings set org.gnome.desktop.peripherals.touchpad send-events 'disabled-on-external-mouse'
    gsettings set org.gnome.desktop.peripherals.touchpad tap-to-click true

- name: Create a temporary directory for Gogh
  ansible.builtin.tempfile:
    state: directory
  register: gogh

- name: Git checkout Gogh-Co repository
  ansible.builtin.git:
    repo: "https://github.com/Gogh-Co/Gogh.git"
    dest: "{{ gogh.path }}"

- name: Configure gnome-terminal
  ansible.builtin.shell: |
    gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:{{gterminal_profile.stdout}}/ font 'Fira Code 14'
    gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:{{gterminal_profile.stdout}}/ use-system-font false
    gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:{{gterminal_profile.stdout}}/ audible-bell false
    gsettings set org.gnome.Terminal.Legacy.Keybindings:/org/gnome/terminal/legacy/keybindings/ next-tab '<Primary>Tab'
    gsettings set org.gnome.Terminal.Legacy.Keybindings:/org/gnome/terminal/legacy/keybindings/ prev-tab '<Primary><Shift>Tab'

- name: Install home files
  ansible.builtin.file:
    src: "{{ (role_path, 'files', item) | path_join }}"
    dest: "{{ (home, item) | path_join }}"
    state: link
  loop:
    - .zsh
    - .zshrc
    - .zshenv
    - .aliases
    - .gitconfig
    - .bkp_ignorelist

- name: Configure weechat
  ansible.builtin.file:
    src: "{{ (role_path, 'files', 'weechat') | path_join }}"
    dest: "{{ (home, '.config', 'weechat') | path_join }}"
    state: link

- name: Create gpg and ssh config directories
  ansible.builtin.file:
    dest: "{{ (home, item) | path_join }}"
    state: directory
    mode: 0700
  loop:
    - .ssh
    - .gnupg

- name: Configure gpg agent
  ansible.builtin.file:
    src: "{{ (role_path, 'files', 'gpg-agent.conf') | path_join }}"
    dest: "{{ (home, '.gnupg', 'gpg-agent.conf') | path_join }}"
    state: link
