---
- name: Install home files
  ansible.builtin.file:
    src: "{{ (role_path, 'files', item) | path_join }}"
    dest: "{{ (home, item) | path_join }}"
    state: link
  loop:
    - .zsh
    - .zshrc
    - .zshenv
    - .aliases
    - .bkp_ignorelist

- name: Configure weechat
  ansible.builtin.file:
    src: "{{ (role_path, 'files', 'weechat') | path_join }}"
    dest: "{{ (home, '.config', 'weechat') | path_join }}"
    state: link

- name: Create gpg and ssh config directories
  ansible.builtin.file:
    dest: "{{ (home, item) | path_join }}"
    state: directory
    mode: 0700
  loop:
    - .ssh
    - .gnupg

- name: Configure gpg agent
  ansible.builtin.file:
    src: "{{ (role_path, 'files', 'gpg-agent.conf') | path_join }}"
    dest: "{{ (home, '.gnupg', 'gpg-agent.conf') | path_join }}"
    state: link

- name: "Configure KDE specific tasks"
  ansible.builtin.include_tasks: "kde.yml"