---
- name: Configure app-switcher
  ansible.builtin.shell: gsettings set org.gnome.shell.app-switcher current-workspace-only true

- name: Enable user extensions
  ansible.builtin.shell: gsettings set org.gnome.shell disable-user-extensions false

- name: Configure CAPS LOCK as an additional control
  ansible.builtin.shell: gsettings set org.gnome.desktop.input-sources xkb-options "['caps:ctrl_modifier', 'shift:both_capslock_cancel']"

- name: Set vim as default editor ($VISUAL / $EDITOR)
  ansible.builtin.shell: update-alternatives --set editor /usr/bin/vim.basic
  when: distribution == 'debian'

# You need to restart gnome to update the extensions installed list and
# After that you can run the bootstrap.sh again
# If your are using xrog, you can try to reload gnome (do not work for wayland)
- name: Enable gnome extensions
  ansible.builtin.shell: "{{ item }}"
  loop:
    - gnome-extensions enable "$(gnome-extensions list | grep drive-menu)"
    - gnome-extensions enable "$(gnome-extensions list | grep dash-to-dock)"
    - gnome-extensions enable "$(gnome-extensions list | grep appindicator)"
  ignore_errors: true

- name: Configure dark mode
  ansible.builtin.shell: "{{ item }}"
  loop:
    - gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-dark'
    - gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'

- name: Configure touchpad
  ansible.builtin.shell: "{{ item }}"
  loop:
    - gsettings set org.gnome.desktop.peripherals.touchpad send-events 'disabled-on-external-mouse'
    - gsettings set org.gnome.desktop.peripherals.touchpad tap-to-click true

# https://askubuntu.com/questions/1036473/ubuntu-18-how-to-cha nge-screenshot-application-to-flameshot
- name: Configure flameshot as default screenshot tool
  ansible.builtin.shell: "{{ item }}"
  loop:
    - gsettings set org.gnome.shell.keybindings show-screenshot-ui '[]'
    - gsettings set org.gnome.settings-daemon.plugins.media-keys custom-keybindings "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/']"
    - gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ name 'flameshot'
    - gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ command '/usr/bin/flameshot gui'
    - gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ binding 'Print'

- name: Disable gnome keyring ssh autostart
  ansible.builtin.shell: "{{ item }}"
  loop:
    - cp /etc/xdg/autostart/gnome-keyring-ssh.desktop ~/.config/autostart/
    - echo "Hidden=true" >> ~/.config/autostart/gnome-keyring-ssh.desktop

- name: Create a temporary directory for Gogh
  ansible.builtin.tempfile:
    state: directory
  register: gogh

- name: Git checkout Gogh-Co repository
  ansible.builtin.git:
    repo: "https://github.com/Gogh-Co/Gogh.git"
    dest: "{{ gogh.path }}"

- name: Install one-dark colorscheme for gnome-terminal
  ansible.builtin.shell: "{{ (gogh.path, 'installs', 'one-dark.sh') | path_join }}"
  environment:
    TERMINAL: gnome-terminal

- name: Set gnome-terminal default profile as One Dark
  ansible.builtin.shell: "{{ (role_path, 'files', 'scripts', 'set_default_gnome_terminal_profile.sh') | path_join }}"
  args:
    executable: /bin/bash

- name: Get gnome-terminal default profile
  ansible.builtin.shell: gsettings get org.gnome.Terminal.ProfilesList default
  register: gterminal_profile

- name: Configure gnome-terminal
  ansible.builtin.shell: "{{ item }}"
  loop:
    - "gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:{{gterminal_profile.stdout}}/ font 'Fira Code 14'"
    - "gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:{{gterminal_profile.stdout}}/ use-system-font false"
    - "gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:{{gterminal_profile.stdout}}/ audible-bell false"
    - "gsettings set org.gnome.Terminal.Legacy.Keybindings:/org/gnome/terminal/legacy/keybindings/ next-tab '<Primary>Tab'"
    - "gsettings set org.gnome.Terminal.Legacy.Keybindings:/org/gnome/terminal/legacy/keybindings/ prev-tab '<Primary><Shift>Tab'"

- name: Install home files
  ansible.builtin.file:
    src: "{{ (role_path, 'files', item) | path_join }}"
    dest: "{{ (home, item) | path_join }}"
    state: link
  loop:
    - .zsh
    - .zshrc
    - .zshenv
    - .aliases
    - .gitconfig
    - .bkp_ignorelist

- name: Configure weechat
  ansible.builtin.file:
    src: "{{ (role_path, 'files', 'weechat') | path_join }}"
    dest: "{{ (home, '.config', 'weechat') | path_join }}"
    state: link

- name: Create gpg and ssh config directories
  ansible.builtin.file:
    dest: "{{ (home, item) | path_join }}"
    state: directory
    mode: 0700
  loop:
    - .ssh
    - .gnupg

- name: Configure gpg agent
  ansible.builtin.file:
    src: "{{ (role_path, 'files', 'gpg-agent.conf') | path_join }}"
    dest: "{{ (home, '.gnupg', 'gpg-agent.conf') | path_join }}"
    state: link
