---
- name: Fonts
  become: yes
  block:
    - name: Configure system fonts
      copy:
        src: "{{ role_path }}/files/system/fonts-config"
        dest: /etc/sysconfig/fonts-config
    
    - name: Apply font configuration
      command: fonts-config
  tags: desktop