---
- name: Fonts
  become: yes
  block:
    - name: Configure system fonts
      copy:
        src: "{{ role_path }}/files/system/fonts-config"
        dest: /etc/sysconfig/fonts-config
    
    - name: Apply font configuration
      command: fonts-config
  tags: desktop

- name: Configure papirus folder colors
  block:
    - name: Download papirus folders installer
      get_url:
        url: https://raw.githubusercontent.com/PapirusDevelopmentTeam/papirus-folders/master/install.sh
        dest: /tmp/papirus-folders-install.sh
        mode: '0700'

    - name: Install papirus folders
      command: /tmp/papirus-folders-install.sh

    - name: Define colors to match theme
      command: papirus-folders -C teal --theme Papirus

    - name: Remove papirus folders
      command: env uninstall=true /tmp/papirus-folders-install.sh

    - name: Clean up
      file:
        state: absent
        path: /tmp/papirus-folders-install.sh
  tags: desktop

- name: Configure additional groups
  become: yes
  user:
    append: true
    groups: "{{ item }}"
    name: "{{ lookup('env', 'USER') }}"
  loop:
    - lp
    - audio
    - video
    - nm-openvpn
  tags: desktop
