---
- name: Install desktop packages
  become: true
  block:
    - name: Upgrade packages
      ansible.builtin.dnf:
        name: "*"
        state: latest

    - name: Install packages
      ansible.builtin.dnf:
        name: "{{ packages }}"
        state: latest
  tags:
    - packages
