---
- name: Install desktop packages
  become: true
  block:
    - name: Upgrade packages
      ansible.builtin.dnf:
        name: "*"
        state: latest

    - name: Install packages
      ansible.builtin.dnf:
        name: "{{ packages }}"
        state: latest
  tags:
    - packages

- name: Configure desktop
  ansible.builtin.shell: "{{ item }}"
  loop:
    - gsettings set org.gnome.shell.app-switcher current-workspace-only true
    # Set flameshot as the default screenshot tool
    # https://askubuntu.com/questions/1036473/ubuntu-18-how-to-change-screenshot-application-to-flameshot
    - gsettings set org.gnome.shell.keybindings show-screenshot-ui '[]'
    - gsettings set org.gnome.settings-daemon.plugins.media-keys custom-keybindings "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/']"
    - gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ name 'flameshot'
    - gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ command '/usr/bin/flameshot gui'
    - gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ binding 'Print'
    # disable gnome keyring ssh autostart
    - cp /etc/xdg/autostart/gnome-keyring-ssh.desktop ~/.config/autostart/
    - echo "Hidden=true" >> ~/.config/autostart/gnome-keyring-ssh.desktop
  tags: desktop

- name: Install home files
  ansible.builtin.file:
    src: "{{ (playbook_dir, 'files', item) | path_join }}"
    dest: "{{ (home, item) | path_join }}"
    state: link
  loop:
    - .zsh
    - .zshrc
    - .zshenv
    - .aliases
    - .gitconfig
  tags: home

- name: Create Alacritty config directory
  ansible.builtin.file:
    dest: "{{ (home, '.config', 'alacritty') | path_join }}"
    state: directory
  tags: home

- name: Copy Alacritty configuration file
  ansible.builtin.file:
    src: "{{ (playbook_dir, 'files', 'alacritty', 'alacritty.yml') | path_join }}"
    dest: "{{ (home, '.config', 'alacritty', 'alacritty.yml') | path_join }}"
    state: link
  tags: home