---
- include_tasks: "packages.yml"
  tags:
    - packages
    - repositories

- include_tasks: desktop.yml
  tags: desktop

- name: Install home files
  copy:
    src: "{{ role_path }}/files/home/{{ item }}"
    dest: "{{ home }}"
  loop:
    - .bashrc
    - .bash
    - .profile
    - .aliases
    - .tmux.conf
    - .Xdefaults
  tags: home

- name: Enable and start cups service
  become: yes
  systemd:
    state: started
    enabled: yes
    name: cups
  tags: system

- name: Enable and start samba service
  become: yes
  systemd:
    state: started
    enabled: yes
    name: smb
  tags: system

- name: Configure additional groups
  become: yes
  user:
    append: true
    groups: "{{ item }}"
    name: "{{ lookup('env', 'USER') }}"
  loop:
    - lp
    - audio
    - video
    - nm-openvpn
  tags: system

- name: Set graphical login
  become: true
  command: 'systemctl set-default graphical.target'
  tags: system
