---
- include_tasks: "packages.yml"
  tags:
    - packages
    - repositories

- include_tasks: desktop.yml
  tags: desktop

- name: Install home files
  copy:
    src: "{{ role_path }}/files/home/{{ item }}"
    dest: "{{ home }}"
  loop:
    - .zsh
    - .zshrc
    - .zshenv
    - .aliases
  tags: home