---
- name: "Include {{distribution}} specific tasks"
  ansible.builtin.include_tasks: "{{ distribution }}.yml"
  when: distribution is defined

- name: Configure desktop
  tags: desktop
  block:
    - name: Configure app-switcher
      ansible.builtin.shell: gsettings set org.gnome.shell.app-switcher current-workspace-only true

    # https://askubuntu.com/questions/1036473/ubuntu-18-how-to-change-screenshot-application-to-flameshot
    - name: Configure flameshot as default screenshot tool
      ansible.builtin.shell: "{{ item }}"
      loop:
        - gsettings set org.gnome.shell.keybindings show-screenshot-ui '[]'
        - gsettings set org.gnome.settings-daemon.plugins.media-keys custom-keybindings "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/']"
        - gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ name 'flameshot'
        - gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ command '/usr/bin/flameshot gui'
        - gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ binding 'Print'

    - name: Disable gnome keyring ssh autostart
      ansible.builtin.shell: "{{ item }}"
      loop:
        - cp /etc/xdg/autostart/gnome-keyring-ssh.desktop ~/.config/autostart/
        - echo "Hidden=true" >> ~/.config/autostart/gnome-keyring-ssh.desktop

    - name: Create a temporary directory for Gogh
      ansible.builtin.tempfile:
        state: directory
        suffix: gogh
      register: gogh

    - name: Git checkout Gogh-Co repository
      ansible.builtin.git:
        repo: "https://github.com/Gogh-Co/Gogh.git"
        dest: "{{ gogh.path }}"

    - name: Install one-dark colorscheme for gnome-terminal
      ansible.builtin.shell: "{{ (gogh.path, 'installs', 'one-dark.sh') | path_join }}"
      environment:
        TERMINAL: gnome-terminal

    - name: Set gnome-terminal default profile as One Dark
      ansible.builtin.shell: "{{ (playbook_dir, 'files', 'scripts', 'set_default_gnome_terminal_profile.sh') | path_join }}"
      args:
        executable: /bin/bash

    - name: Get gnome-terminal default profile
      ansible.builtin.shell: gsettings get org.gnome.Terminal.ProfilesList default
      register: gterminal_profile

    - name: Configure gnome-terminal
      ansible.builtin.shell: "{{ item }}"
      loop:
        - "gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:{{gterminal_profile.stdout}}/ font 'Fira Code 14'"
        - "gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:{{gterminal_profile.stdout}}/ use-system-font false"
        - "gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:{{gterminal_profile.stdout}}/ audible-bell false"

- name: Install home files
  ansible.builtin.file:
    src: "{{ (playbook_dir, 'files', item) | path_join }}"
    dest: "{{ (home, item) | path_join }}"
    state: link
  loop:
    - .zsh
    - .zshrc
    - .zshenv
    - .aliases
    - .gitconfig
    - .bkp_ignorelist
  tags: home

- name: Create gpg and ssh config directories
  ansible.builtin.file:
    dest: "{{ (home, item) | path_join }}"
    state: directory
    mode: 0700
  loop:
    - .ssh
    - .gnupg
  tags: home

- name: Configure gpg agent
  ansible.builtin.file:
    src: "{{ (playbook_dir, 'files', 'gpg-agent.conf') | path_join }}"
    dest: "{{ (home, '.gnupg', 'gpg-agent.conf') | path_join }}"
    state: link
  tags: home

- name: Create dev structure
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ (home, 'dev', 'src', 'github.com') | path_join }}"
    - "{{ (home, 'dev', 'src', 'gitlab.com') | path_join }}"
    - "{{ (home, 'dev', 'src', 'dev.azure.com') | path_join }}"
  tags: git

- name: Create gitconfig for each 'git host provider'
  block:
    - name: Configure github.com user and email
      ansible.builtin.file:
        src: "{{ (playbook_dir, 'files', 'gitconfig_include', '.gitconfig_github') | path_join }}"
        dest: "{{ (home, 'dev', 'src', 'github.com', '.gitconfig') | path_join }}"
        state: link

    - name: Configure gitlab.com user and email
      ansible.builtin.file:
        src: "{{ (playbook_dir, 'files', 'gitconfig_include', '.gitconfig_gitlab') | path_join }}"
        dest: "{{ (home, 'dev', 'src', 'gitlab.com', '.gitconfig') | path_join }}"
        state: link

    - name: Configure dev.azure.com user and email
      ansible.builtin.file:
        src: "{{ (playbook_dir, 'files', 'gitconfig_include', '.gitconfig_azure') | path_join }}"
        dest: "{{ (home, 'dev', 'src', 'dev.azure.com', '.gitconfig') | path_join }}"
        state: link
