---
- name: 'Refresh all repos'
  become: yes
  zypper_repository:
    repo: '*'
    runrefresh: yes
  tags:
    - packages

- name: Install desktop packages
  become: yes
  block:
    - name: Upgrade packages
      zypper:
        name: "*"
        state: latest
        update_cache: yes

    - name: Install packages
      zypper:
        name: "{{ packages }}"
        state: latest
        disable_recommends: no
        force: yes
  tags:
    - packages
