---
- name: Install desktop packages
  become: yes
  block:
    - name: Upgrade packages
      apt:
        name: "*"
        state: latest
        update_cache: yes

    - name: Install packages
      apt:
        name: "{{ packages }}"
        state: latest
  tags:
    - packages
