---
- name: Download Brave Browser key
  ansible.builtin.get_url:
    url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
    dest: /usr/share/keyrings/brave-browser-archive-keyring.gpg
    force: true
    mode: "644"

- name: Download Brave Browser repository sources
  ansible.builtin.get_url:
    url: https://brave-browser-apt-release.s3.brave.com/brave-browser.sources
    dest: /etc/apt/sources.list.d/brave-browser-release.sources
    force: true
    mode: "644"

- name: Install Brave Browser
  ansible.builtin.apt:
    name: brave-browser
    state: latest
    update_cache: true
