---
- name: Remove some uneeded packages
  ansible.builtin.apt:
    name:
      - "libreoffice-*"
      - "rhythmbox*"
      - shotwell
    state: absent
    purge: true

- name: Downalod and Install minikube
  block:
    - name: Download minikube
      ansible.builtin.get_url:
        url: https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb
        dest: /tmp/minikube.deb

    - name: Install minikube
      ansible.builtin.apt:
        deb: /tmp/minikube.deb
  when: "'minikube' not in ansible_facts.packages"

- name: Add Docker gpg apt key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: "{{trusted_gpg_path}}/docker.asc"
    mode: "0644"
    force: true

- name: Add Microsoft gpg apt key
  ansible.builtin.get_url:
    url: https://packages.microsoft.com/keys/microsoft.asc
    dest: "{{trusted_gpg_path}}/microsoft.asc"
    mode: "0644"
    force: true

- name: Add Google gpg apt key
  ansible.builtin.get_url:
    url: https://dl.google.com/linux/linux_signing_key.pub
    dest: "{{trusted_gpg_path}}/google.asc"
    mode: "0644"
    force: true

- name: Add Weechat gpg apt key
  ansible.builtin.get_url:
    url: https://weechat.org/dev/info/debian_repository_signing_key/
    dest: "{{trusted_gpg_path}}/weechat.gpg"
    mode: "0644"
    force: true

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/debian bookworm stable
    filename: docker

- name: Add VSCode repository
  ansible.builtin.apt_repository:
    repo: deb https://packages.microsoft.com/repos/vscode stable main
    filename: vscode

- name: Add Google Chrome repository
  ansible.builtin.apt_repository:
    repo: deb https://dl.google.com/linux/chrome/deb/ stable main
    filename: google-chrome

- name: Add Weechat repository
  ansible.builtin.apt_repository:
    repo: deb https://weechat.org/debian bookworm main
    filename: weechat

- name: Upgrade packages
  ansible.builtin.apt:
    name: "*"
    state: latest
    update_cache: true

- name: Install packages
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: latest

- name: Set vim as default editor ($VISUAL / $EDITOR)
  ansible.builtin.shell: update-alternatives --set editor /usr/bin/vim.basic
