---
- name: Upgrade packages
  ansible.builtin.dnf:
    name: "*"
    state: latest

- name: Install packages
  ansible.builtin.dnf:
    name: "{{ packages }}"
    state: latest

- name: Add docker-ce repository
  ansible.builtin.shell: sudo dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo

- name: Import Microsoft rpm key
  ansible.builtin.rpm_key:
    state: present
    key: https://packages.microsoft.com/keys/microsoft.asc

- name: Add VSCode repository
  ansible.builtin.shell: sudo dnf config-manager --add-repo https://packages.microsoft.com/yumrepos/vscode

- name: Enable google-chrome repository
  ansible.builtin.shell: sudo dnf config-manager --set-enabled google-chrome
