---
- name: Upgrade packages
  ansible.builtin.dnf:
    name: "*"
    state: latest

- name: Install packages
  ansible.builtin.dnf:
    name: "{{ packages }}"
    state: latest

- name: Add docker-ce repository
  ansible.builtin.shell: sudo dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
