---
- name: Check if firefox repository key is already downloaded
  stat:
    path: "{{trusted_gpg_path}}/packages.mozilla.org.asc "
  register: firefox_key

- name: Add Firefox repository gpg apt key
  ansible.builtin.get_url:
    url: https://packages.mozilla.org/apt/repo-signing-key.gpg
    dest: "{{trusted_gpg_path}}/packages.mozilla.org.asc"
    mode: "0644"
    force: true
  when: not firefox_key.stat.exists

- name: Add Firefox repository
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/etc/apt/keyrings/packages.mozilla.org.asc] https://packages.mozilla.org/apt mozilla main
    filename: mozilla

- name: Configure APT to prioritize packages from the Mozilla repository
  ansible.builtin.copy:
    src: preferences.d/mozilla
    dest: /etc/apt/preferences.d/mozilla

- name: Install Firefox from Mozilla
  ansible.builtin.apt:
    name: firefox
    state: latest
