---
- name: Include distribution variables
  ansible.builtin.include_vars: "{{distribution}}.yml"

- name: "Include {{distribution}} specific tasks"
  ansible.builtin.include_tasks: "{{ distribution }}.yml"
  when: distribution is defined

- name: Install flatpak packages
  ansible.builtin.shell: flatpak install -y {{ item }}
  loop: "{{ flatpak_packages }}"

- name: Add user to the docker group
  ansible.builtin.user:
    append: true
    groups: docker
    name: "{{ user }}"

- name: Enable docker
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    enabled: true
  loop:
    - docker
    - containerd
