---
- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Remove some uneeded packages
  ansible.builtin.apt:
    name:
      - "libreoffice-*"
      - "firefox-esr*"
      - "rhythmbox*"
      - shotwell
      - gnome-console
    state: absent
    purge: true

# During the installation I set the default to en_US, but i need some
# pt_BR locales (data, time and so on)
- name: Configure locale
  ansible.builtin.shell: |
    sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen
    sed -i -e 's/# pt_BR.UTF-8 UTF-8/pt_BR.UTF-8 UTF-8/' /etc/locale.gen

    cat <<EOF > /etc/default/locale
    LANG=en_US.UTF-8
    LANGUAGE=en_US:en
    EOF

    dpkg-reconfigure --frontend=noninteractive locales
    update-locale LANG=en_US.UTF-8

- name: Upgrade packages
  ansible.builtin.apt:
    name: "*"
    state: latest
    update_cache: true

- name: Install packages
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: latest

- name: Configure flathub
  ansible.builtin.shell: flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Install flatpak packages
  ansible.builtin.shell: flatpak install -y {{ item }}
  loop: "{{ flatpak_packages }}"
  when: flatpak_packages is defined

- include_tasks: fonts.yml
- include_tasks: firefox.yml
- include_tasks: docker.yml
- include_tasks: weechat.yml
- include_tasks: k8s.yml
- include_tasks: ghcli.yml

- name: Download and Install VSCode
  block:
    - name: Download VSCode package
      ansible.builtin.get_url:
        url: https://go.microsoft.com/fwlink/?LinkID=760868
        dest: /tmp/vscode.deb
        force: true

    - name: Install VSCode
      ansible.builtin.apt:
        deb: /tmp/vscode.deb
  ignore_errors: true
  when: "'code' not in ansible_facts.packages"

- name: Download and install Google Chrome
  block:
    - name: Download Google Chrome package
      ansible.builtin.get_url:
        url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        dest: /tmp/google_chrome.deb
        force: true

    - name: Install Google Chrome
      ansible.builtin.apt:
        deb: /tmp/google_chrome.deb
  ignore_errors: true
  when: "'google-chrome-stable' not in ansible_facts.packages"

- name: Cleanup remaining packages
  ansible.builtin.apt:
    autoremove: true

- name: Set vim as default editor ($VISUAL / $EDITOR)
  ansible.builtin.shell: update-alternatives --set editor /usr/bin/vim.basic
