---
- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Include distribution variables
  ansible.builtin.include_vars: "{{distribution}}.yml"

- name: "Include {{distribution}} specific tasks"
  ansible.builtin.include_tasks: "{{ distribution }}.yml"
  when: distribution is defined

- name: Configure flathub
  ansible.builtin.shell: flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Install flatpak packages
  ansible.builtin.shell: flatpak install -y {{ item }}
  loop: "{{ flatpak_packages }}"

- name: Check if kubectl is installed
  stat:
    path: /usr/local/bin/kubectl
  register: kubectl_path

- name: Download and install kubectl
  block:
    - name: Get kubectl latest stable version string
      shell: curl -L -s https://dl.k8s.io/release/stable.txt
      register: kubectl_version

    - name: Download and install kubectl
      ansible.builtin.get_url:
        url: "https://dl.k8s.io/release/{{ kubectl_version.stdout }}/bin/linux/amd64/kubectl"
        dest: /usr/local/bin/kubectl
        mode: "0755"
  when: not kubectl_path.stat.exists

- name: Add user to the docker group
  ansible.builtin.user:
    append: true
    groups: docker
    name: "{{ user }}"

- name: Enable docker
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    enabled: true
  loop:
    - docker
    - containerd
