---
- name: Add WeeChat repository using deb822 format
  ansible.builtin.deb822_repository:
    name: weechat
    types: deb
    uris: https://weechat.org/debian
    suites: "{{ ansible_facts['distribution_release'] }}"
    components: main
    architectures: amd64
    signed_by: https://weechat.org/dev/info/debian_repository_signing_key/
    state: present

- name: Install Weechat packages
  ansible.builtin.apt:
    name:
      - weechat-curses
      - weechat-plugins
    state: latest
