---
trusted_gpg_path: /etc/apt/keyrings
packages:
  - gnome-core
  - network-manager-gnome
  - gnome-tweaks
  - gnome-text-editor
  - apt-transport-https
  - firmware-linux-nonfree
  - build-essential
  - fonts-firacode
  - uuid-runtime
  - vim
  - jq
  - flameshot
  - flatpak
  - gnome-software-plugin-flatpak
  - gnome-shell-extensions-extra
  - gnome-shell-extension-dashtodock
  - gnome-shell-extension-appindicator
  - docker-ce
  - weechat-curses
  - weechat-plugins
  - vivaldi-stable

flathub_packages:
  - com.bitwarden.desktop
