---
- name: Create directory structure
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ (home, 'dev', 'src', 'github.com') | path_join }}"
    - "{{ (home, 'dev', 'src', 'gitlab.com') | path_join }}"
    - "{{ (home, 'dev', 'src', 'dev.azure.com') | path_join }}"

- name: Global gitconfig file
  ansible.builtin.file:
    src: "{{ (role_path, 'files', '.gitconfig') | path_join }}"
    dest: "{{ (home, '.gitconfig') | path_join }}"
    state: link

- name: Configure github.com user and email
  ansible.builtin.file:
    src: "{{ (role_path, 'files', 'gitconfig_include', '.gitconfig_github') | path_join }}"
    dest: "{{ (home, 'dev', 'src', 'github.com', '.gitconfig') | path_join }}"
    state: link

- name: Configure gitlab.com user and email
  ansible.builtin.file:
    src: "{{ (role_path, 'files', 'gitconfig_include', '.gitconfig_gitlab') | path_join }}"
    dest: "{{ (home, 'dev', 'src', 'gitlab.com', '.gitconfig') | path_join }}"
    state: link

- name: Configure dev.azure.com user and email
  ansible.builtin.file:
    src: "{{ (role_path, 'files', 'gitconfig_include', '.gitconfig_azure') | path_join }}"
    dest: "{{ (home, 'dev', 'src', 'dev.azure.com', '.gitconfig') | path_join }}"
    state: link

- name: Configure minikube with docker
  ansible.builtin.shell: minikube config set driver docker

- name: Download NVM install script
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh
    dest: /tmp/nvm-install.sh

- name: Download pyenv install script
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/pyenv/pyenv-installer/master/bin/pyenv-installer
    dest: /tmp/pyenv-installer

- name: Download rbenv install script
  ansible.builtin.get_url:
    url: https://github.com/rbenv/rbenv-installer/raw/HEAD/bin/rbenv-installer
    dest: /tmp/rbenv-installer

- name: Install NVM - Node Version Manager
  ansible.builtin.shell: bash /tmp/nvm-install.sh

- name: Install pyenv - Python Version Manager
  ansible.builtin.shell: bash /tmp/pyenv-installer

- name: Install rbenv - Ruby Version Manager
  ansible.builtin.shell: bash /tmp/rbenv-installer
