#!/usr/bin/env zsh

if ! type -p aws > /dev/null
then
    echo "aws cli not installed"
    return 1
fi

awscli=$(type -p aws | cut -d' ' -f3)

if (( $# < 1)) ; then
    echo "Custom AWS CLI wrapper"
    echo
    echo "Custom Commands: login, ssh, stsdecode"
    echo

    if read -q "show_help?Do you want to see the default aws cli help? (y/n) " ; then
        $awscli
    fi

    return 1
fi

local command="$1"; shift 1

case $command in
    "login")
        if typeset -f awslogin > /dev/null ; then
            awslogin "$@"
        else
            echo "login not implemented"
        fi
        ;;
    "ssh")
        instance_id="$1"
        $awscli ssm start-session --target "$instance_id"
        ;;
    "stsdecode")
        message="$1"
        $awscli sts decode-authorization-message \
            --encoded-message "$message" \
            --query DecodedMessage \
            --output text | jq '.'
        ;;
    *)
        $awscli "$command" "$@"
        ;;
esac