#!/usr/bin/env zsh

# these are local functions you create well... locally
# they are not checked in to the repo
if [[ -d "$HOME/.zsh/vpng.local" ]]; then
    for i in "$HOME"/.zsh/vpng.local/*.zsh; do
        source $i
    done
fi

if (( $# < 1)) ; then
    echo "Usage: vpng <vpn_name>"

    return 1
fi

local vpn_name="$1"; shift 1

if typeset -f vpnlogin > /dev/null ; then
    vpnlogin "$vpn_name" "$@"
else
    echo "vpnlogin not implemented"
fi