#!/bin/bash

function _stop() {
    # Terminate already running bar instances
    killall -q polybar

    # Wait until the processes have been shut down
    while pgrep -u ${UID} -x polybar >/dev/null; do sleep 1; done
}

function _start() {
    local _primary
    local _screens
    local _displays

    _displays=$( xrandr | grep "connected" )
    _screens=$( xrandr | grep -E "\bconnected\b" | cut -d ' ' -f 1 )

	if [[ "$(echo "${_screens}" | wc -l)" == 1 ]]
    then
        _primary="${_screens}"
    else
        _primary="$(echo "${_displays}" | grep primary | cut -d ' ' -f 1 )"
        # fallback to built-in monitor
        [[ -z ${_primary}  ]] && _primary="$( echo "${_screens}" | grep -iE 'edp-?1' )"
	fi

    PRIMARY_MONITOR="${_primary}" polybar primary &

    mapfile -t _screens < <( echo "${_screens}" | grep -v "${_primary}" )

    for _screen in "${_screens[@]}"
    do
        [[ ${_screen} ]] && SECONDARY_MONITOR=${_screen} polybar simple &
    done

    echo "Bars launched..."
}

function main() {
    local _opt

    _opt="$1"

    case ${_opt} in
        start)
            _start
            ;;
        stop)
            _stop
            ;;
        restart)
            _stop
            _start
            ;;
    esac
}

main "$@"
